package dev.simplified.classbuilder.editor;

import com.intellij.psi.CommonClassNames;
import com.intellij.psi.JavaPsiFacade;
import com.intellij.psi.JavaRecursiveElementWalkingVisitor;
import com.intellij.psi.PsiAnnotation;
import com.intellij.psi.PsiAssignmentExpression;
import com.intellij.psi.PsiClass;
import com.intellij.psi.PsiClassInitializer;
import com.intellij.psi.PsiClassType;
import com.intellij.psi.PsiCodeBlock;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiEllipsisType;
import com.intellij.psi.PsiExpression;
import com.intellij.psi.PsiExpressionStatement;
import com.intellij.psi.PsiField;
import com.intellij.psi.PsiJavaCodeReferenceElement;
import com.intellij.psi.PsiMember;
import com.intellij.psi.PsiMethod;
import com.intellij.psi.PsiMethodCallExpression;
import com.intellij.psi.PsiModifier;
import com.intellij.psi.PsiParameter;
import com.intellij.psi.PsiPrimitiveType;
import com.intellij.psi.PsiReferenceExpression;
import com.intellij.psi.PsiStatement;
import com.intellij.psi.PsiSubstitutor;
import com.intellij.psi.PsiSuperExpression;
import com.intellij.psi.PsiThisExpression;
import com.intellij.psi.PsiType;
import com.intellij.psi.PsiTypeElement;
import com.intellij.psi.PsiTypeParameter;
import com.intellij.psi.PsiTypes;
import com.intellij.psi.PsiVariable;
import com.intellij.psi.controlFlow.AnalysisCanceledException;
import com.intellij.psi.controlFlow.ControlFlow;
import com.intellij.psi.controlFlow.ControlFlowFactory;
import com.intellij.psi.controlFlow.ControlFlowUtil;
import com.intellij.psi.controlFlow.LocalsOrMyInstanceFieldsControlFlowPolicy;
import com.intellij.psi.impl.source.PsiExtensibleClass;
import com.intellij.psi.util.PsiTypesUtil;
import com.intellij.psi.util.PsiUtil;
import com.intellij.psi.util.TypeConversionUtil;
import dev.simplified.accessor.inspect.AccessorConstants;
import dev.simplified.args.inspect.ArgsConstants;
import dev.simplified.classbuilder.apt.AccessorScheme;
import dev.simplified.classbuilder.apt.DeclaredBuilderShape;
import dev.simplified.classbuilder.apt.InheritedMethod;
import dev.simplified.classbuilder.apt.InstanceDefaults;
import dev.simplified.classbuilder.apt.SetterScheme;
import dev.simplified.classbuilder.apt.SetterShape;
import dev.simplified.classbuilder.apt.SlotHolding;
import dev.simplified.classbuilder.inspect.ClassBuilderConstants;
import dev.simplified.shared.psi.WrittenAnnotations;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The editor's reading of the storage a merged builder holds each slot in, and
 * the diagnostics that follow from it - a declared field mistyped for its slot
 * or {@code final} under a setter the merge appends, an author method covering a
 * setter with a parameter the copy entry points cannot pass the slot to, and an
 * appended seed field a constructor leaves unassigned or assigns again.
 *
 * <p>The comparison and the sentence are {@link DeclaredBuilderShape#mistypedSlot},
 * the one the processor reports, and the classification is {@link SlotHolding#of}
 * over the rule {@link InstanceDefaults} states; what lives here is reading the
 * facts both ask of from PSI the way the processor reads them from the tree - the
 * names a field's initializer spells, and the instance members the target
 * declares, inherits and has generated by the accessor passes. A slot is rendered
 * in the form it is held in: its declared type, a supplier of it, or the
 * {@code java.util} scratch container a collected slot whose default reads
 * instance state gathers into.
 */
public final class MergedSlotStorage {

    private MergedSlotStorage() {
    }

    /**
     * A declared builder field the merge cannot assign, with the diagnostic the
     * processor prints for it.
     *
     * @param field the author's field in the declared builder
     * @param message the diagnostic text
     */
    public record Mistyped(@NotNull PsiField field, @NotNull String message) { }

    /**
     * Reports each field of a declared builder whose type is not the storage type
     * of the slot it shares a name with, or which is declared {@code final} under
     * a slot one of whose generated setters is appended to assign it.
     *
     * <p>Reads the slots with the extractor the builder synthesis uses, so the
     * set of names judged is the set the merge assigns - the target's fields or
     * record components, or the annotated member's parameters. A {@code final}
     * field is judged by {@link DeclaredBuilderShape#finalSlot} over the keys of
     * the setters synthesised for its slot, each with its shape, and of the
     * author's own methods, the ones the augment provider compares. Not for use
     * from an augment provider: the slot types are rendered through their
     * canonical text, which resolves.
     *
     * @param target the type the builder nests in
     * @param executable the annotated constructor or static factory, or {@code null} when the
     *     annotation is on the type
     * @param declared the builder it declares
     * @param annotation the {@code @ClassBuilder}, wherever it is written
     * @return the mistyped fields, in the declared builder's field order
     */
    public static @NotNull List<Mistyped> mistypedFields(@NotNull PsiClass target,
                                                          @Nullable PsiMethod executable,
                                                          @NotNull PsiClass declared,
                                                          @NotNull PsiAnnotation annotation) {
        String declaredName = declared.getName();
        if (declaredName == null) return List.of();
        SetterScheme setters =
            GeneratedMemberFactory.EditorBuilderConfig.fromAnnotation(annotation).setters();
        List<PsiFieldShape> slots;
        if (executable != null) {
            slots = PsiFieldShapeExtractor.fromExecutable(executable, PsiSubstitutor.EMPTY, setters);
        } else {
            Set<String> excluded = GeneratedMemberFactory.excludedNames(target);
            slots = target.isRecord()
                ? PsiFieldShapeExtractor.fromRecord(target, excluded, setters)
                : PsiFieldShapeExtractor.fromClass(target, excluded, setters);
        }

        GeneratedMemberFactory.EditorBuilderConfig config =
            GeneratedMemberFactory.EditorBuilderConfig.fromAnnotation(annotation);
        boolean retainInit = config.retainInit();
        Map<String, List<GeneratedMemberFactory.SlotSetter>> slotSetters = null;
        Set<String> authorKeys = null;
        List<Mistyped> out = new ArrayList<>();
        for (PsiField field : ownFields(declared)) {
            String written = writtenTypeText(field);
            if (written == null) continue;
            for (PsiFieldShape slot : slots) {
                if (!slot.name.equals(field.getName())) continue;
                if (field.hasModifierProperty(PsiModifier.FINAL)) {
                    // Synthesised once, and only where a final field asks.
                    if (slotSetters == null) {
                        slotSetters = GeneratedMemberFactory.settersBySlot(
                            new BuilderSite(target, executable, annotation), config, declared);
                        authorKeys = authorKeys(declared);
                    }
                    Map<String, SetterShape> generated = new LinkedHashMap<>();
                    for (GeneratedMemberFactory.SlotSetter setter : slotSetters.getOrDefault(slot.name, List.of()))
                        generated.put(generatedKey(setter.method()), setter.shape());
                    String finalSlot = DeclaredBuilderShape.finalSlot(declaredName, slot.name, generated,
                        slot.append, authorKeys);
                    if (finalSlot != null) {
                        out.add(new Mistyped(field, finalSlot));
                        continue;
                    }
                }
                // A parameter carries no initializer and cannot be lazy, so the
                // merge holds it as declared - a field of the enclosing type
                // sharing its name is no part of it.
                SlotHolding holding = executable != null
                    ? SlotHolding.DECLARED
                    : holdingOf(target, slot, retainInit);
                String message = DeclaredBuilderShape.mistypedSlot(declaredName, slot.name,
                    written, storageTypeText(slot, holding), holding);
                if (message != null) out.add(new Mistyped(field, message));
            }
        }
        return out;
    }

    /**
     * An author method of a declared builder that covers a generated setter
     * with a parameter the copy entry points cannot pass the slot to, with the
     * diagnostic the processor prints for it.
     *
     * @param method the author's method
     * @param message the diagnostic text
     */
    public record CoveringMethod(@NotNull PsiMethod method, @NotNull String message) { }

    /**
     * Reports each method of a declared builder that covers a generated setter
     * under {@link DeclaredBuilderShape#methodKey} while taking another
     * parameterisation of the same generic type, where {@code from(T)} or
     * {@code mutate()} is emitted to pass it the slot's own type.
     *
     * <p>The rule and its wording are
     * {@link DeclaredBuilderShape#setterWithOtherTypeArguments}, asked of the
     * author's parameter types as written and the synthesised setter's
     * presentable ones - the keys the augment provider compares - of the
     * setter's shape, which decides whether the copy entry points call it, and
     * of the copy entry points {@link GeneratedMemberFactory#copyEntryPoints}
     * names. Not for use from an augment provider: the setters are synthesised,
     * which resolves the slot types.
     *
     * @param target the type the builder nests in
     * @param executable the annotated constructor or static factory, or {@code null} when the
     *     annotation is on the type
     * @param declared the builder it declares
     * @param annotation the {@code @ClassBuilder}, wherever it is written
     * @return the covering methods, in the declared builder's method order
     */
    public static @NotNull List<CoveringMethod> settersCoveredWithOtherTypeArguments(
        @NotNull PsiClass target, @Nullable PsiMethod executable, @NotNull PsiClass declared,
        @NotNull PsiAnnotation annotation) {
        String declaredName = declared.getName();
        if (declaredName == null) return List.of();
        BuilderSite site = new BuilderSite(target, executable, annotation);
        GeneratedMemberFactory.EditorBuilderConfig config =
            GeneratedMemberFactory.EditorBuilderConfig.fromAnnotation(annotation);
        List<String> copyEntryPoints = GeneratedMemberFactory.copyEntryPoints(site, config);
        if (copyEntryPoints.isEmpty()) return List.of();

        Map<String, GeneratedMemberFactory.SlotSetter> generated = new HashMap<>();
        for (List<GeneratedMemberFactory.SlotSetter> setters
            : GeneratedMemberFactory.settersBySlot(site, config, declared).values()) {
            for (GeneratedMemberFactory.SlotSetter setter : setters)
                generated.putIfAbsent(generatedKey(setter.method()), setter);
        }
        List<String> typeParameters = new ArrayList<>();
        for (PsiTypeParameter parameter : declared.getTypeParameters()) typeParameters.add(parameter.getName());

        List<CoveringMethod> out = new ArrayList<>();
        for (PsiMethod own : GeneratedMemberFactory.ownMethods(declared)) {
            if (own.isConstructor()) continue;
            GeneratedMemberFactory.SlotSetter covered = generated.get(writtenKey(own));
            if (covered == null) continue;
            String message = DeclaredBuilderShape.setterWithOtherTypeArguments(declaredName, own.getName(),
                covered.shape(), writtenTypes(own), presentableTypes(covered.method()), typeParameters,
                copyEntryPoints);
            if (message != null) out.add(new CoveringMethod(own, message));
        }
        return out;
    }

    /**
     * Reports each generated setter the merge appends into a declared builder
     * that a method the builder inherits keeps from overriding it.
     *
     * <p>The rule and its wording are
     * {@link DeclaredBuilderShape#unoverridableInheritedMethod}, asked of every
     * synthesised setter no author method covers under
     * {@link DeclaredBuilderShape#methodKey} - the setters the augment provider
     * contributes - and of the methods the builder inherits, read as the
     * processor reads them from the element model: see
     * {@link #inheritedMethods}. Not for use from an augment provider: the
     * supertypes are resolved.
     *
     * @param target the type the builder nests in
     * @param executable the annotated constructor or static factory, or {@code null} when the
     *     annotation is on the type
     * @param declared the builder it declares
     * @param annotation the {@code @ClassBuilder}, wherever it is written
     * @return the diagnostic text for each blocked setter, in synthesis order
     */
    public static @NotNull List<String> unoverridableInheritedMethods(@NotNull PsiClass target,
                                                                      @Nullable PsiMethod executable,
                                                                      @NotNull PsiClass declared,
                                                                      @NotNull PsiAnnotation annotation) {
        String declaredName = declared.getName();
        if (declaredName == null) return List.of();
        BuilderSite site = new BuilderSite(target, executable, annotation);
        GeneratedMemberFactory.EditorBuilderConfig config =
            GeneratedMemberFactory.EditorBuilderConfig.fromAnnotation(annotation);
        Set<String> authorKeys = authorKeys(declared);
        List<InheritedMethod> inherited = null;
        List<String> out = new ArrayList<>();
        for (List<GeneratedMemberFactory.SlotSetter> setters
            : GeneratedMemberFactory.settersBySlot(site, config, declared).values()) {
            for (GeneratedMemberFactory.SlotSetter setter : setters) {
                PsiMethod method = setter.method();
                if (authorKeys.contains(generatedKey(method))) continue;
                if (inherited == null) inherited = inheritedMethods(declared);
                String message = DeclaredBuilderShape.unoverridableInheritedMethod(declaredName, method.getName(),
                    presentableTypes(method), inherited);
                if (message != null) out.add(message);
            }
        }
        return out;
    }

    /**
     * The methods a declared builder inherits, read as the processor reads them.
     *
     * <p>Its supertypes are walked depth first, each superclass ahead of the
     * interfaces beside it, with {@code java.lang.Object} read last; a private
     * or static method, and a package-private one declared in another package,
     * is not inherited and is left out. Each method is read as a member of the
     * builder through the supertype's substitutor, so a self-typed supertype's
     * {@code B} is the builder itself, and its return type accepts the builder
     * where the builder is assignable to it or to its erasure. A supertype's own
     * methods are read without the augment pass, as the element model holds
     * only what a supertype compiled in the same round declares in source.
     *
     * @param declared the builder the author wrote
     * @return the inherited methods, in the order the supertypes are walked
     */
    private static List<InheritedMethod> inheritedMethods(PsiClass declared) {
        JavaPsiFacade facade = JavaPsiFacade.getInstance(declared.getProject());
        List<PsiClass> supertypes = new ArrayList<>();
        collectSupertypes(declared, supertypes, new HashSet<>());
        PsiClass object = facade.findClass(CommonClassNames.JAVA_LANG_OBJECT, declared.getResolveScope());
        if (object != null) supertypes.add(object);
        PsiClassType builderType = PsiTypesUtil.getClassType(declared);

        List<InheritedMethod> out = new ArrayList<>();
        for (PsiClass supertype : supertypes) {
            boolean samePackage = facade.arePackagesTheSame(supertype, declared);
            PsiSubstitutor substitutor =
                TypeConversionUtil.getSuperClassSubstitutor(supertype, declared, PsiSubstitutor.EMPTY);
            for (PsiMethod method : GeneratedMemberFactory.ownMethods(supertype)) {
                PsiType declaredReturn = method.getReturnType();
                if (method.isConstructor() || declaredReturn == null) continue;
                if (method.hasModifierProperty(PsiModifier.PRIVATE) || method.hasModifierProperty(PsiModifier.STATIC))
                    continue;
                if (!samePackage && !method.hasModifierProperty(PsiModifier.PUBLIC)
                    && !method.hasModifierProperty(PsiModifier.PROTECTED)) continue;
                List<String> parameters = new ArrayList<>();
                for (PsiParameter parameter : method.getParameterList().getParameters()) {
                    PsiType member = substitutor.substitute(parameter.getType());
                    parameters.add(TypeConversionUtil.erasure(member == null ? parameter.getType() : member)
                        .getCanonicalText());
                }
                PsiType returned = substitutor.substitute(declaredReturn);
                boolean accepts = returned != null && !(returned instanceof PsiPrimitiveType)
                    && (returned.isAssignableFrom(builderType)
                        || TypeConversionUtil.erasure(returned).isAssignableFrom(builderType));
                out.add(new InheritedMethod(method.getName(), parameters, String.valueOf(supertype.getName()),
                    declaredReturn.getCanonicalText(), method.hasModifierProperty(PsiModifier.FINAL), accepts));
            }
        }
        return out;
    }

    /**
     * Collects every supertype of a class but {@code java.lang.Object}, depth
     * first, each once.
     *
     * @param type the class whose supertypes are collected
     * @param out the supertypes collected so far, appended to
     * @param seen the classes already collected
     */
    private static void collectSupertypes(PsiClass type, List<PsiClass> out, Set<PsiClass> seen) {
        for (PsiClassType direct : type.getSuperTypes()) {
            PsiClass resolved = direct.resolve();
            if (resolved == null || CommonClassNames.JAVA_LANG_OBJECT.equals(resolved.getQualifiedName())) continue;
            if (!seen.add(resolved)) continue;
            out.add(resolved);
            collectSupertypes(resolved, out, seen);
        }
    }

    /**
     * The key an author method is compared under, from its parameter types as
     * written.
     *
     * @param method a method the author declared
     * @return its {@link DeclaredBuilderShape#methodKey}
     */
    static @NotNull String writtenKey(@NotNull PsiMethod method) {
        return DeclaredBuilderShape.methodKey(method.getName(), writtenTypes(method));
    }

    /**
     * The key a synthesised method is compared under, from the presentable text
     * of its parameter types - rendered from the names they were built with
     * rather than resolved.
     *
     * @param method a method the editor synthesised
     * @return its {@link DeclaredBuilderShape#methodKey}
     */
    static @NotNull String generatedKey(@NotNull PsiMethod method) {
        return DeclaredBuilderShape.methodKey(method.getName(), presentableTypes(method));
    }

    /** Every {@link #writtenKey} the declared builder's own methods carry. */
    private static Set<String> authorKeys(PsiClass declared) {
        Set<String> out = new HashSet<>();
        for (PsiMethod own : GeneratedMemberFactory.ownMethods(declared)) out.add(writtenKey(own));
        return out;
    }

    /** Each parameter's type as written, in order. */
    private static List<String> writtenTypes(PsiMethod method) {
        List<String> types = new ArrayList<>();
        for (PsiParameter parameter : method.getParameterList().getParameters()) {
            String written = writtenTypeText(parameter);
            types.add(written == null ? "" : written);
        }
        return types;
    }

    /** Each parameter's type in its presentable text, in order. */
    private static List<String> presentableTypes(PsiMethod method) {
        List<String> types = new ArrayList<>();
        for (PsiParameter parameter : method.getParameterList().getParameters())
            types.add(parameter.getType().getPresentableText());
        return types;
    }

    /**
     * A seed the merge appends as a {@code final} field and the declared builder
     * assigns other than exactly once, with where to report it.
     *
     * @param anchor the constructor that leaves it unassigned or assigns it after an instance
     *     initializer, the assignment javac reports as a second one, or the builder's name when it
     *     declares no constructor at all or an appended constructor leaves the seed unassigned
     * @param message the diagnostic text
     */
    public record MisassignedSeed(@NotNull PsiElement anchor, @NotNull String message) { }

    /**
     * Names the annotated member's seeds, each of which {@code builder(..)} takes
     * and passes to the builder's constructor.
     *
     * @param executable the annotated constructor or static factory
     * @return the seeded parameters' names, in parameter order
     */
    public static @NotNull List<String> seedNames(@NotNull PsiMethod executable) {
        List<String> out = new ArrayList<>();
        for (PsiParameter parameter : executable.getParameterList().getParameters()) {
            if (PsiFieldShapeExtractor.hasAnnotation(parameter, ClassBuilderConstants.BUILDER_SEED_FQN))
                out.add(parameter.getName());
        }
        return out;
    }

    /**
     * The type of each of the annotated member's seeds as written, in the order
     * {@code builder(..)} takes them and passes them to the builder's
     * constructor.
     *
     * @param executable the annotated constructor or static factory
     * @return the seeded parameters' types, in parameter order
     */
    public static @NotNull List<String> seedTypes(@NotNull PsiMethod executable) {
        List<String> out = new ArrayList<>();
        for (PsiParameter parameter : executable.getParameterList().getParameters()) {
            if (!PsiFieldShapeExtractor.hasAnnotation(parameter, ClassBuilderConstants.BUILDER_SEED_FQN))
                continue;
            String written = writtenTypeText(parameter);
            out.add(written == null ? "" : written);
        }
        return out;
    }

    /**
     * Reports each seed the merge appends into a declared builder that a
     * constructor there leaves unassigned, or may assign where it is already
     * assigned.
     *
     * <p>The merge appends a seed as a {@code final} field and never appends the
     * constructor that assigns it, so the builder's constructors have to, each
     * exactly once. javac refuses one that does not assign it - and the implicit
     * default of a class declaring none - and one that may assign it a second
     * time, on a line the author wrote; the platform's own check reads only
     * fields written in source, so without this the editor is green over both.
     * Assignment is answered by the platform's definite-assignment flow over
     * each constructor body and each instance initializer, which run before
     * every constructor body: one that definitely assigns the seed leaves no
     * constructor responsible for it, and one that may assign it leaves no
     * constructor free to. A constructor delegating through {@code this(..)} has
     * the seed assigned by the one it calls, so any assignment of its own is a
     * second one, and a constructor may assign it twice itself - on two paths
     * that meet, or inside a loop - both reported on the assignment javac
     * reports. A seed the author declares a field for is the platform's to
     * check, that field being written in source. Wherever a flow cannot be
     * built, nothing is reported.
     *
     * <p>A constructor a constructor annotation appends onto the builder is one
     * of its constructors too. The constructor pass runs before the merge, so it
     * takes the builder's fields as they stand then and never the seed, and
     * javac refuses it on the builder's line wherever no instance initializer
     * assigns the seed; it is read through {@link ArgsConstants#appended}, as the
     * entry-point gate reads it, and reported on the builder's name.
     *
     * <p>Not for use from an augment provider: it reads the builder's fields
     * through the augment-aware lookup, which is what finds the appended ones.
     *
     * @param executable the annotated constructor or static factory
     * @param declared the builder the enclosing type declares
     * @return the misassigned seeds, in parameter order
     */
    public static @NotNull List<MisassignedSeed> misassignedSeeds(@NotNull PsiMethod executable,
                                                                  @NotNull PsiClass declared) {
        String declaredName = declared.getName();
        PsiElement nameAnchor = declared.getNameIdentifier();
        if (declaredName == null || nameAnchor == null) return List.of();
        if (!(declared instanceof PsiExtensibleClass extensible)) return List.of();
        List<PsiCodeBlock> initializers = new ArrayList<>();
        for (PsiClassInitializer initializer : declared.getInitializers()) {
            if (!initializer.hasModifierProperty(PsiModifier.STATIC)) initializers.add(initializer.getBody());
        }
        List<PsiMethod> constructors = new ArrayList<>();
        for (PsiMethod own : extensible.getOwnMethods()) {
            if (own.isConstructor()) constructors.add(own);
        }
        List<ArgsConstants.AppendedConstructor> appendedConstructors = ArgsConstants.appended(declared);

        List<MisassignedSeed> out = new ArrayList<>();
        for (PsiParameter parameter : executable.getParameterList().getParameters()) {
            if (!PsiFieldShapeExtractor.hasAnnotation(parameter, ClassBuilderConstants.BUILDER_SEED_FQN))
                continue;
            String seed = parameter.getName();
            if (declaresField(extensible, seed)) continue;
            PsiField appended = declared.findFieldByName(seed, false);
            if (appended == null) continue;
            boolean initialized = assignedByAnInitializer(initializers, appended);
            if (constructors.isEmpty() && appendedConstructors.isEmpty()) {
                if (!initialized) {
                    out.add(new MisassignedSeed(nameAnchor,
                        DeclaredBuilderShape.unassignedSeed(declaredName, seed, false)));
                }
                continue;
            }
            if (!initialized) {
                for (ArgsConstants.AppendedConstructor constructor : appendedConstructors) {
                    List<String> types = new ArrayList<>();
                    for (PsiField field : constructor.parameters()) {
                        String written = writtenTypeText(field);
                        types.add(written == null ? "" : written);
                    }
                    out.add(new MisassignedSeed(nameAnchor, DeclaredBuilderShape.unassignedByAppendedConstructor(
                        declaredName, seed, constructor.mode().annotationName(), types)));
                }
            }
            boolean mayBeInitialized = mayBeAssignedByAnInitializer(initializers, appended);
            for (PsiMethod constructor : constructors) {
                PsiCodeBlock body = constructor.getBody();
                if (body == null) continue;
                if (delegates(body)) {
                    PsiReferenceExpression write = definitelyLeavesUnassigned(body, appended)
                        ? null
                        : firstWrite(body, appended);
                    if (write != null) {
                        out.add(new MisassignedSeed(write, DeclaredBuilderShape.reassignedSeed(declaredName, seed,
                            DeclaredBuilderShape.PriorAssignment.DELEGATED_CONSTRUCTOR)));
                    }
                    continue;
                }
                PsiElement anchor = constructor.getNameIdentifier();
                if (anchor == null) anchor = constructor;
                if (mayBeInitialized && !definitelyLeavesUnassigned(body, appended)) {
                    out.add(new MisassignedSeed(anchor, DeclaredBuilderShape.reassignedSeed(declaredName, seed,
                        DeclaredBuilderShape.PriorAssignment.INSTANCE_INITIALIZER)));
                    continue;
                }
                PsiReferenceExpression again = assignedAgain(body, appended);
                if (again != null) {
                    out.add(new MisassignedSeed(again, DeclaredBuilderShape.reassignedSeed(declaredName, seed,
                        DeclaredBuilderShape.PriorAssignment.SAME_CONSTRUCTOR)));
                }
                if (!initialized && !definitelyAssigns(body, appended)) {
                    out.add(new MisassignedSeed(anchor,
                        DeclaredBuilderShape.unassignedSeed(declaredName, seed, true)));
                }
            }
        }
        return out;
    }

    /**
     * The first assignment to the field a block spells, in source order.
     *
     * @param body the block to read
     * @param field the field it may assign
     * @return the assigned reference, or {@code null} when the block spells none
     */
    private static @Nullable PsiReferenceExpression firstWrite(PsiCodeBlock body, PsiField field) {
        List<PsiReferenceExpression> writes = writesOf(body, field);
        return writes.isEmpty() ? null : writes.get(0);
    }

    /**
     * The assignment to the field that a block may make where it has already
     * assigned it - a second assignment on a path through an earlier one, which
     * javac reports as possibly already assigned, or one inside a loop, which it
     * reports as possibly assigned in the loop.
     *
     * @param body the constructor body to analyse
     * @param field the appended seed field
     * @return the first such assignment, or {@code null} when there is none or the analysis cannot finish
     */
    private static @Nullable PsiReferenceExpression assignedAgain(PsiCodeBlock body, PsiField field) {
        ControlFlow flow = flowOf(body);
        if (flow == null) return null;
        List<PsiReferenceExpression> writes = writesOf(body, field);
        for (ControlFlowUtil.VariableInfo twice : ControlFlowUtil.getInitializedTwice(flow)) {
            PsiElement element = twice.expression instanceof PsiAssignmentExpression assignment
                ? assignment.getLExpression()
                : twice.expression;
            if (element instanceof PsiReferenceExpression reference && writes.contains(reference)) return reference;
        }
        for (PsiReferenceExpression write : writes)
            if (ControlFlowUtil.isVariableAssignedInLoop(write, field)) return write;
        return null;
    }

    /**
     * Every assignment to the field a block spells, in source order.
     *
     * @param body the block to read
     * @param field the field it may assign
     * @return each assigned reference to the field
     */
    private static List<PsiReferenceExpression> writesOf(PsiCodeBlock body, PsiField field) {
        List<PsiReferenceExpression> out = new ArrayList<>();
        body.accept(new JavaRecursiveElementWalkingVisitor() {
            @Override
            public void visitReferenceExpression(@NotNull PsiReferenceExpression expression) {
                super.visitReferenceExpression(expression);
                if (PsiUtil.isAccessedForWriting(expression) && expression.isReferenceTo(field)) out.add(expression);
            }
        });
        return out;
    }

    /** Whether the author wrote a field of that name in the builder. */
    private static boolean declaresField(PsiExtensibleClass declared, String name) {
        for (PsiField own : declared.getOwnFields()) {
            if (name.equals(own.getName())) return true;
        }
        return false;
    }

    /**
     * Whether an instance initializer leaves the field definitely assigned.
     *
     * <p>The initializers run in order before every constructor body, so the
     * field is assigned once any one of them assigns it.
     *
     * @param initializers the bodies of the builder's instance initializers, in declaration order
     * @param field the appended seed field
     * @return whether one of them assigns it
     */
    private static boolean assignedByAnInitializer(List<PsiCodeBlock> initializers, PsiField field) {
        for (PsiCodeBlock body : initializers) {
            if (definitelyAssigns(body, field)) return true;
        }
        return false;
    }

    /**
     * Whether an instance initializer may leave the field assigned, on any
     * path.
     *
     * @param initializers the bodies of the builder's instance initializers, in declaration order
     * @param field the appended seed field
     * @return whether one of them may assign it
     */
    private static boolean mayBeAssignedByAnInitializer(List<PsiCodeBlock> initializers, PsiField field) {
        for (PsiCodeBlock body : initializers) {
            if (!definitelyLeavesUnassigned(body, field)) return true;
        }
        return false;
    }

    /**
     * Whether a constructor body opens by delegating through {@code this(..)},
     * which leaves the fields to the constructor it calls.
     *
     * @param body the constructor's body
     * @return whether its first statement is a {@code this(..)} call
     */
    private static boolean delegates(PsiCodeBlock body) {
        PsiStatement[] statements = body.getStatements();
        return statements.length > 0
            && statements[0] instanceof PsiExpressionStatement first
            && first.getExpression() instanceof PsiMethodCallExpression call
            && "this".equals(call.getMethodExpression().getReferenceName());
    }

    /**
     * Whether a block leaves the field definitely assigned, by the platform's
     * definite-assignment flow.
     *
     * @param body the block to analyse
     * @param field the field it may assign
     * @return whether it assigns the field on every path, and {@code true} when the analysis cannot finish
     */
    private static boolean definitelyAssigns(PsiCodeBlock body, PsiField field) {
        ControlFlow flow = flowOf(body);
        return flow == null || ControlFlowUtil.isVariableDefinitelyAssigned(field, flow);
    }

    /**
     * Whether a block assigns the field on no path, by the platform's
     * definite-assignment flow.
     *
     * @param body the block to analyse
     * @param field the field it may assign
     * @return whether it never assigns the field, and {@code true} when the analysis cannot finish
     */
    private static boolean definitelyLeavesUnassigned(PsiCodeBlock body, PsiField field) {
        ControlFlow flow = flowOf(body);
        return flow == null || ControlFlowUtil.isVariableDefinitelyNotAssigned(field, flow);
    }

    /** The block's control flow over locals and the class's own fields, or {@code null} when it cannot be built. */
    private static @Nullable ControlFlow flowOf(PsiCodeBlock body) {
        try {
            return ControlFlowFactory.getInstance(body.getProject())
                .getControlFlow(body, LocalsOrMyInstanceFieldsControlFlowPolicy.getInstance());
        } catch (AnalysisCanceledException e) {
            return null;
        }
    }

    /**
     * How the merge holds a slot of a class or record target, as the processor
     * classifies it.
     *
     * <p>The classification is {@link SlotHolding#of}, asked of the flags the
     * processor asks it of. The instance-default flag is
     * {@link InstanceDefaults#readsInstanceState}, asked of the names the field's
     * initializer spells and of the instance members the target declares and
     * inherits, and only where {@link InstanceDefaults#captures} says the
     * initializer is kept at all. Nothing here resolves a reference, which is
     * what lets the augment provider ask it: the names are read as written and
     * the members off each type's own declarations.
     *
     * @param target the annotated type
     * @param slot the slot to classify
     * @param retainInit the class-wide policy written on {@code @ClassBuilder}
     * @return how the slot is held
     */
    static @NotNull SlotHolding holdingOf(@NotNull PsiClass target, @NotNull PsiFieldShape slot,
                                          boolean retainInit) {
        boolean collected = slot.collector && (slot.isListLike || slot.isMap);
        return SlotHolding.of(slot.lazy, collected, instanceDefault(target, slot, retainInit));
    }

    /**
     * The slot's declared type as the processor reads it - a varargs
     * parameter's as the array it is.
     *
     * @param slot the slot
     * @return the declared type, never an ellipsis type
     */
    static @NotNull PsiType declaredType(@NotNull PsiFieldShape slot) {
        return slot.type instanceof PsiEllipsisType ellipsis ? ellipsis.toArrayType() : slot.type;
    }

    /**
     * Renders the type the merge holds a slot in, as the processor renders it.
     *
     * <p>A supplier is {@link DeclaredBuilderShape#supplierOf} the declared type
     * and a scratch container {@link DeclaredBuilderShape#scratchContainerOf}
     * the element, key and value types the slot's shape read off its matched
     * {@code java.util} supertype - the two renderings the processor prints.
     * Every type is rendered through its canonical text, which names what is
     * written without resolving it further than the shape already has.
     *
     * @param slot the slot
     * @param holding how the slot is held, per {@link #holdingOf}
     * @return the storage type
     */
    static @NotNull String storageTypeText(@NotNull PsiFieldShape slot, @NotNull SlotHolding holding) {
        if (holding == SlotHolding.COLLECTED_SCRATCH) {
            return DeclaredBuilderShape.scratchContainerOf(slot.isMap, slot.isSet,
                canonicalText(slot.collectionElement), canonicalText(slot.mapKey), canonicalText(slot.mapValue));
        }
        String declared = declaredType(slot).getCanonicalText();
        return holding.isSupplier() ? DeclaredBuilderShape.supplierOf(declared) : declared;
    }

    /** A type argument's canonical text, or {@code null} where the shape read none. */
    private static @Nullable String canonicalText(@Nullable PsiType type) {
        return type == null ? null : type.getCanonicalText();
    }

    /**
     * Whether the slot's field keeps an initializer that reads instance state.
     *
     * @param target the annotated type
     * @param slot the slot to classify
     * @param retainInit the class-wide policy written on {@code @ClassBuilder}
     * @return whether the slot's default is computed on the instance
     */
    private static boolean instanceDefault(PsiClass target, PsiFieldShape slot, boolean retainInit) {
        PsiField field = null;
        for (PsiField own : ownFields(target)) {
            if (slot.name.equals(own.getName())) field = own;
        }
        PsiExpression initializer = field == null ? null : field.getInitializer();
        if (initializer == null) return false;
        PsiAnnotation written = WrittenAnnotations.findOnMember(field, ClassBuilderConstants.BUILDER_DEFAULT_FQN);
        boolean builderDefault = InstanceDefaults.builderDefault(
            written == null ? null : ClassBuilderConstants.booleanAttr(written, "value", true), retainInit);
        if (!InstanceDefaults.captures(builderDefault, slot.collector && slot.isCustomContainer)) return false;
        return InstanceDefaults.readsInstanceState(spelledNames(initializer), instanceMemberNames(target));
    }

    /**
     * Lists every name an initializer spells without a qualifier, and
     * {@code this} for each {@code this} expression, qualified or not - the
     * names the processor lists from the tree.
     *
     * @param initializer the field's initializer
     * @return the names, in source order
     */
    private static List<String> spelledNames(PsiExpression initializer) {
        List<String> out = new ArrayList<>();
        initializer.accept(new JavaRecursiveElementWalkingVisitor() {
            @Override
            public void visitReferenceElement(@NotNull PsiJavaCodeReferenceElement reference) {
                String name = reference.getReferenceName();
                if (reference.getQualifier() == null && name != null) out.add(name);
                super.visitReferenceElement(reference);
            }

            @Override
            public void visitReferenceExpression(@NotNull PsiReferenceExpression expression) {
                visitReferenceElement(expression);
            }

            @Override
            public void visitThisExpression(@NotNull PsiThisExpression expression) {
                out.add("this");
                super.visitThisExpression(expression);
            }

            @Override
            public void visitSuperExpression(@NotNull PsiSuperExpression expression) {
                // A qualified super is a select on the tree, whose name the
                // processor does not list.
                if (expression.getQualifier() == null) out.add("super");
                super.visitSuperExpression(expression);
            }
        });
        return out;
    }

    /**
     * Names every non-static field and method the target declares, and every
     * one its supertypes declare that it inherits, as the processor's element
     * model lists them - and every instance accessor another pass generates on
     * any of them, which neither model lists.
     *
     * @param target the annotated type
     * @return the member names
     */
    private static Set<String> instanceMemberNames(PsiClass target) {
        Set<String> names = new HashSet<>();
        collectInstanceMembers(target, true, names, new HashSet<>());
        return names;
    }

    /**
     * Adds a type's instance members to the set, then its supertypes'.
     *
     * <p>The accessors {@code @Getter}, {@code @Setter} and {@code @Lazy}
     * generate are provider members, which the type's own declarations leave
     * out, so they are named from the annotations written on each field and on
     * the type through {@link InstanceDefaults#generatedAccessorNames} - the
     * rule the processor asks of the same annotations. The annotations are
     * matched by their written names and read without resolving.
     *
     * @param type the type to read
     * @param own whether it is the target itself, whose private members count too
     * @param names the set being filled
     * @param visited the types already read
     */
    private static void collectInstanceMembers(PsiClass type, boolean own, Set<String> names,
                                               Set<PsiClass> visited) {
        if (!visited.add(type)) return;
        PsiAnnotation typeGetter = WrittenAnnotations.findOnMember(type, AccessorConstants.GETTER_FQN);
        PsiAnnotation typeSetter = WrittenAnnotations.findOnMember(type, AccessorConstants.SETTER_FQN);
        for (PsiField field : ownFields(type)) {
            if (instanceMember(field, own)) names.add(field.getName());
            PsiAnnotation getter = WrittenAnnotations.findOnMember(field, AccessorConstants.GETTER_FQN);
            PsiAnnotation setter = WrittenAnnotations.findOnMember(field, AccessorConstants.SETTER_FQN);
            names.addAll(InstanceDefaults.generatedAccessorNames(field.getName(),
                PsiTypes.booleanType().equals(field.getType()),
                field.hasModifierProperty(PsiModifier.STATIC),
                schemeOf(getter != null ? getter : typeGetter),
                schemeOf(setter != null ? setter : typeSetter),
                schemeOf(WrittenAnnotations.findOnMember(field, AccessorConstants.LAZY_FQN))));
        }
        for (PsiMethod method : GeneratedMemberFactory.ownMethods(type)) {
            if (!method.isConstructor() && instanceMember(method, own)) names.add(method.getName());
        }
        PsiClass superClass = type.getSuperClass();
        if (superClass != null) collectInstanceMembers(superClass, false, names, visited);
        for (PsiClass implemented : type.getInterfaces()) collectInstanceMembers(implemented, false, names, visited);
    }

    /** The naming scheme an accessor annotation writes, or {@code null} where there is no annotation. */
    private static @Nullable AccessorScheme schemeOf(@Nullable PsiAnnotation annotation) {
        return annotation == null
            ? null
            : AccessorScheme.resolve(AccessorConstants.style(annotation), AccessorConstants.name(annotation));
    }

    /** Whether the member is one the target sees on an instance - its own, or an inherited non-private one. */
    private static boolean instanceMember(PsiMember member, boolean own) {
        if (member.hasModifierProperty(PsiModifier.STATIC)) return false;
        return own || !member.hasModifierProperty(PsiModifier.PRIVATE);
    }

    /**
     * A variable's type as written, with the brackets a C-style declaration puts
     * after its name.
     *
     * <p>javac folds {@code String tags[]} into the declared type, so the
     * processor reads {@code String[]}; the type element PSI keeps in front of
     * the name covers {@code String} alone. The trailing dimensions are counted
     * off the variable's type, which PSI builds from the same brackets without
     * resolving anything.
     *
     * @param variable the field or parameter
     * @return the type as the processor reads it, or {@code null} when none is written
     */
    public static @Nullable String writtenTypeText(@NotNull PsiVariable variable) {
        PsiTypeElement written = variable.getTypeElement();
        if (written == null) return null;
        int trailing = variable.getType().getArrayDimensions() - written.getType().getArrayDimensions();
        return written.getText() + "[]".repeat(Math.max(0, trailing));
    }

    /** The class's own fields, without anything a provider contributed. */
    private static List<PsiField> ownFields(PsiClass declared) {
        return declared instanceof PsiExtensibleClass extensible
            ? extensible.getOwnFields()
            : List.of(declared.getFields());
    }

}
