package dev.simplified.classbuilder.editor;

import com.intellij.psi.JavaRecursiveElementWalkingVisitor;
import com.intellij.psi.PsiAnnotation;
import com.intellij.psi.PsiClass;
import com.intellij.psi.PsiClassInitializer;
import com.intellij.psi.PsiCodeBlock;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiEllipsisType;
import com.intellij.psi.PsiExpression;
import com.intellij.psi.PsiExpressionStatement;
import com.intellij.psi.PsiField;
import com.intellij.psi.PsiJavaCodeReferenceElement;
import com.intellij.psi.PsiMember;
import com.intellij.psi.PsiMethod;
import com.intellij.psi.PsiMethodCallExpression;
import com.intellij.psi.PsiModifier;
import com.intellij.psi.PsiParameter;
import com.intellij.psi.PsiReferenceExpression;
import com.intellij.psi.PsiStatement;
import com.intellij.psi.PsiSubstitutor;
import com.intellij.psi.PsiSuperExpression;
import com.intellij.psi.PsiThisExpression;
import com.intellij.psi.PsiType;
import com.intellij.psi.PsiTypeElement;
import com.intellij.psi.PsiTypes;
import com.intellij.psi.PsiVariable;
import com.intellij.psi.controlFlow.AnalysisCanceledException;
import com.intellij.psi.controlFlow.ControlFlow;
import com.intellij.psi.controlFlow.ControlFlowFactory;
import com.intellij.psi.controlFlow.ControlFlowUtil;
import com.intellij.psi.controlFlow.LocalsOrMyInstanceFieldsControlFlowPolicy;
import com.intellij.psi.impl.source.PsiExtensibleClass;
import dev.simplified.accessor.inspect.AccessorConstants;
import dev.simplified.classbuilder.apt.AccessorScheme;
import dev.simplified.classbuilder.apt.DeclaredBuilderShape;
import dev.simplified.classbuilder.apt.InstanceDefaults;
import dev.simplified.classbuilder.apt.SetterScheme;
import dev.simplified.classbuilder.apt.SlotHolding;
import dev.simplified.classbuilder.inspect.ClassBuilderConstants;
import dev.simplified.shared.psi.WrittenAnnotations;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * The editor's reading of the storage a merged builder holds each slot in, and
 * the diagnostics that follow from it - a declared field mistyped for its slot,
 * and an appended seed field a constructor leaves unassigned or assigns again.
 *
 * <p>The comparison and the sentence are {@link DeclaredBuilderShape#mistypedSlot},
 * the one the processor reports, and the classification is {@link SlotHolding#of}
 * over the rule {@link InstanceDefaults} states; what lives here is reading the
 * facts both ask of from PSI the way the processor reads them from the tree - the
 * names a field's initializer spells, and the instance members the target
 * declares, inherits and has generated by the accessor passes. A slot is rendered
 * in the form it is held in: its declared type, a supplier of it, or the
 * {@code java.util} scratch container a collected slot whose default reads
 * instance state gathers into.
 */
public final class MergedSlotStorage {

    private MergedSlotStorage() {
    }

    /**
     * A declared builder field the merge cannot assign, with the diagnostic the
     * processor prints for it.
     *
     * @param field the author's field in the declared builder
     * @param message the diagnostic text
     */
    public record Mistyped(@NotNull PsiField field, @NotNull String message) { }

    /**
     * Reports each field of a declared builder whose type is not the storage type
     * of the slot it shares a name with, or which is declared {@code final} under
     * a slot the generated setter assigns.
     *
     * <p>Reads the slots with the extractor the builder synthesis uses, so the
     * set of names judged is the set the merge assigns - the target's fields or
     * record components, or the annotated member's parameters. Not for use from
     * an augment provider: the slot types are rendered through their canonical
     * text, which resolves.
     *
     * @param target the type the builder nests in
     * @param executable the annotated constructor or static factory, or {@code null} when the
     *     annotation is on the type
     * @param declared the builder it declares
     * @param annotation the {@code @ClassBuilder}, wherever it is written
     * @return the mistyped fields, in the declared builder's field order
     */
    public static @NotNull List<Mistyped> mistypedFields(@NotNull PsiClass target,
                                                          @Nullable PsiMethod executable,
                                                          @NotNull PsiClass declared,
                                                          @NotNull PsiAnnotation annotation) {
        String declaredName = declared.getName();
        if (declaredName == null) return List.of();
        SetterScheme setters =
            GeneratedMemberFactory.EditorBuilderConfig.fromAnnotation(annotation).setters();
        List<PsiFieldShape> slots;
        if (executable != null) {
            slots = PsiFieldShapeExtractor.fromExecutable(executable, PsiSubstitutor.EMPTY, setters);
        } else {
            Set<String> excluded = GeneratedMemberFactory.excludedNames(target);
            slots = target.isRecord()
                ? PsiFieldShapeExtractor.fromRecord(target, excluded, setters)
                : PsiFieldShapeExtractor.fromClass(target, excluded, setters);
        }

        boolean retainInit =
            GeneratedMemberFactory.EditorBuilderConfig.fromAnnotation(annotation).retainInit();
        List<Mistyped> out = new ArrayList<>();
        for (PsiField field : ownFields(declared)) {
            String written = writtenTypeText(field);
            if (written == null) continue;
            for (PsiFieldShape slot : slots) {
                if (!slot.name.equals(field.getName())) continue;
                // A seed is appended final itself and assigned by the author's
                // constructor alone; every other slot the setter assigns.
                if (field.hasModifierProperty(PsiModifier.FINAL) && !slot.seed) {
                    out.add(new Mistyped(field, DeclaredBuilderShape.finalSlot(declaredName, slot.name)));
                    continue;
                }
                // A parameter carries no initializer and cannot be lazy, so the
                // merge holds it as declared - a field of the enclosing type
                // sharing its name is no part of it.
                SlotHolding holding = executable != null
                    ? SlotHolding.DECLARED
                    : holdingOf(target, slot, retainInit);
                String message = DeclaredBuilderShape.mistypedSlot(declaredName, slot.name,
                    written, storageTypeText(slot, holding), holding);
                if (message != null) out.add(new Mistyped(field, message));
            }
        }
        return out;
    }

    /**
     * A seed the merge appends as a {@code final} field and the declared builder
     * assigns other than exactly once, with where to report it.
     *
     * @param anchor the constructor that leaves it unassigned or assigns it again, or the
     *     builder's name when it declares no constructor at all
     * @param message the diagnostic text
     */
    public record MisassignedSeed(@NotNull PsiElement anchor, @NotNull String message) { }

    /**
     * Names the annotated member's seeds, each of which {@code builder(..)} takes
     * and passes to the builder's constructor.
     *
     * @param executable the annotated constructor or static factory
     * @return the seeded parameters' names, in parameter order
     */
    public static @NotNull List<String> seedNames(@NotNull PsiMethod executable) {
        List<String> out = new ArrayList<>();
        for (PsiParameter parameter : executable.getParameterList().getParameters()) {
            if (PsiFieldShapeExtractor.hasAnnotation(parameter, ClassBuilderConstants.BUILDER_SEED_FQN))
                out.add(parameter.getName());
        }
        return out;
    }

    /**
     * The type of each of the annotated member's seeds as written, in the order
     * {@code builder(..)} takes them and passes them to the builder's
     * constructor.
     *
     * @param executable the annotated constructor or static factory
     * @return the seeded parameters' types, in parameter order
     */
    public static @NotNull List<String> seedTypes(@NotNull PsiMethod executable) {
        List<String> out = new ArrayList<>();
        for (PsiParameter parameter : executable.getParameterList().getParameters()) {
            if (!PsiFieldShapeExtractor.hasAnnotation(parameter, ClassBuilderConstants.BUILDER_SEED_FQN))
                continue;
            String written = writtenTypeText(parameter);
            out.add(written == null ? "" : written);
        }
        return out;
    }

    /**
     * Reports each seed the merge appends into a declared builder that a
     * constructor there leaves unassigned, or assigns after an instance
     * initializer may already have.
     *
     * <p>The merge appends a seed as a {@code final} field and never appends the
     * constructor that assigns it, so the author's constructors have to, each
     * exactly once. javac refuses one that does not assign it - and the implicit
     * default of a class declaring none - and one that assigns it where an
     * instance initializer may already have, on a line the author wrote; the
     * platform's own check reads only fields written in source, so without this
     * the editor is green over both. Assignment is answered by the platform's
     * definite-assignment flow over each constructor body and each instance
     * initializer, which run before every constructor body: one that definitely
     * assigns the seed leaves no constructor responsible for it, and one that may
     * assign it leaves no constructor free to. A constructor delegating through
     * {@code this(..)} is left to the one it calls. A seed the author declares a
     * field for is the platform's to check, that field being written in source.
     *
     * <p>Not for use from an augment provider: it reads the builder's fields
     * through the augment-aware lookup, which is what finds the appended ones.
     *
     * @param executable the annotated constructor or static factory
     * @param declared the builder the enclosing type declares
     * @return the misassigned seeds, in parameter order
     */
    public static @NotNull List<MisassignedSeed> misassignedSeeds(@NotNull PsiMethod executable,
                                                                  @NotNull PsiClass declared) {
        String declaredName = declared.getName();
        PsiElement nameAnchor = declared.getNameIdentifier();
        if (declaredName == null || nameAnchor == null) return List.of();
        if (!(declared instanceof PsiExtensibleClass extensible)) return List.of();
        List<PsiCodeBlock> initializers = new ArrayList<>();
        for (PsiClassInitializer initializer : declared.getInitializers()) {
            if (!initializer.hasModifierProperty(PsiModifier.STATIC)) initializers.add(initializer.getBody());
        }
        List<PsiMethod> constructors = new ArrayList<>();
        for (PsiMethod own : extensible.getOwnMethods()) {
            if (own.isConstructor()) constructors.add(own);
        }

        List<MisassignedSeed> out = new ArrayList<>();
        for (PsiParameter parameter : executable.getParameterList().getParameters()) {
            if (!PsiFieldShapeExtractor.hasAnnotation(parameter, ClassBuilderConstants.BUILDER_SEED_FQN))
                continue;
            String seed = parameter.getName();
            if (declaresField(extensible, seed)) continue;
            PsiField appended = declared.findFieldByName(seed, false);
            if (appended == null) continue;
            boolean initialized = assignedByAnInitializer(initializers, appended);
            if (constructors.isEmpty()) {
                if (!initialized) {
                    out.add(new MisassignedSeed(nameAnchor,
                        DeclaredBuilderShape.unassignedSeed(declaredName, seed, false)));
                }
                continue;
            }
            boolean mayBeInitialized = mayBeAssignedByAnInitializer(initializers, appended);
            for (PsiMethod constructor : constructors) {
                PsiCodeBlock body = constructor.getBody();
                if (body == null || delegates(body)) continue;
                PsiElement anchor = constructor.getNameIdentifier();
                if (anchor == null) anchor = constructor;
                if (mayBeInitialized && !definitelyLeavesUnassigned(body, appended)) {
                    out.add(new MisassignedSeed(anchor, DeclaredBuilderShape.reassignedSeed(declaredName, seed)));
                } else if (!initialized && !definitelyAssigns(body, appended)) {
                    out.add(new MisassignedSeed(anchor,
                        DeclaredBuilderShape.unassignedSeed(declaredName, seed, true)));
                }
            }
        }
        return out;
    }

    /** Whether the author wrote a field of that name in the builder. */
    private static boolean declaresField(PsiExtensibleClass declared, String name) {
        for (PsiField own : declared.getOwnFields()) {
            if (name.equals(own.getName())) return true;
        }
        return false;
    }

    /**
     * Whether an instance initializer leaves the field definitely assigned.
     *
     * <p>The initializers run in order before every constructor body, so the
     * field is assigned once any one of them assigns it.
     *
     * @param initializers the bodies of the builder's instance initializers, in declaration order
     * @param field the appended seed field
     * @return whether one of them assigns it
     */
    private static boolean assignedByAnInitializer(List<PsiCodeBlock> initializers, PsiField field) {
        for (PsiCodeBlock body : initializers) {
            if (definitelyAssigns(body, field)) return true;
        }
        return false;
    }

    /**
     * Whether an instance initializer may leave the field assigned, on any
     * path.
     *
     * @param initializers the bodies of the builder's instance initializers, in declaration order
     * @param field the appended seed field
     * @return whether one of them may assign it
     */
    private static boolean mayBeAssignedByAnInitializer(List<PsiCodeBlock> initializers, PsiField field) {
        for (PsiCodeBlock body : initializers) {
            if (!definitelyLeavesUnassigned(body, field)) return true;
        }
        return false;
    }

    /**
     * Whether a constructor body opens by delegating through {@code this(..)},
     * which leaves the fields to the constructor it calls.
     *
     * @param body the constructor's body
     * @return whether its first statement is a {@code this(..)} call
     */
    private static boolean delegates(PsiCodeBlock body) {
        PsiStatement[] statements = body.getStatements();
        return statements.length > 0
            && statements[0] instanceof PsiExpressionStatement first
            && first.getExpression() instanceof PsiMethodCallExpression call
            && "this".equals(call.getMethodExpression().getReferenceName());
    }

    /**
     * Whether a block leaves the field definitely assigned, by the platform's
     * definite-assignment flow.
     *
     * @param body the block to analyse
     * @param field the field it may assign
     * @return whether it assigns the field on every path, and {@code true} when the analysis cannot finish
     */
    private static boolean definitelyAssigns(PsiCodeBlock body, PsiField field) {
        ControlFlow flow = flowOf(body);
        return flow == null || ControlFlowUtil.isVariableDefinitelyAssigned(field, flow);
    }

    /**
     * Whether a block assigns the field on no path, by the platform's
     * definite-assignment flow.
     *
     * @param body the block to analyse
     * @param field the field it may assign
     * @return whether it never assigns the field, and {@code true} when the analysis cannot finish
     */
    private static boolean definitelyLeavesUnassigned(PsiCodeBlock body, PsiField field) {
        ControlFlow flow = flowOf(body);
        return flow == null || ControlFlowUtil.isVariableDefinitelyNotAssigned(field, flow);
    }

    /** The block's control flow over locals and the class's own fields, or {@code null} when it cannot be built. */
    private static @Nullable ControlFlow flowOf(PsiCodeBlock body) {
        try {
            return ControlFlowFactory.getInstance(body.getProject())
                .getControlFlow(body, LocalsOrMyInstanceFieldsControlFlowPolicy.getInstance());
        } catch (AnalysisCanceledException e) {
            return null;
        }
    }

    /**
     * How the merge holds a slot of a class or record target, as the processor
     * classifies it.
     *
     * <p>The classification is {@link SlotHolding#of}, asked of the flags the
     * processor asks it of. The instance-default flag is
     * {@link InstanceDefaults#readsInstanceState}, asked of the names the field's
     * initializer spells and of the instance members the target declares and
     * inherits, and only where {@link InstanceDefaults#captures} says the
     * initializer is kept at all. Nothing here resolves a reference, which is
     * what lets the augment provider ask it: the names are read as written and
     * the members off each type's own declarations.
     *
     * @param target the annotated type
     * @param slot the slot to classify
     * @param retainInit the class-wide policy written on {@code @ClassBuilder}
     * @return how the slot is held
     */
    static @NotNull SlotHolding holdingOf(@NotNull PsiClass target, @NotNull PsiFieldShape slot,
                                          boolean retainInit) {
        boolean collected = slot.collector && (slot.isListLike || slot.isMap);
        return SlotHolding.of(slot.lazy, collected, instanceDefault(target, slot, retainInit));
    }

    /**
     * The slot's declared type as the processor reads it - a varargs
     * parameter's as the array it is.
     *
     * @param slot the slot
     * @return the declared type, never an ellipsis type
     */
    static @NotNull PsiType declaredType(@NotNull PsiFieldShape slot) {
        return slot.type instanceof PsiEllipsisType ellipsis ? ellipsis.toArrayType() : slot.type;
    }

    /**
     * Renders the type the merge holds a slot in, as the processor renders it.
     *
     * <p>A supplier is {@link DeclaredBuilderShape#supplierOf} the declared type
     * and a scratch container {@link DeclaredBuilderShape#scratchContainerOf}
     * the element, key and value types the slot's shape read off its matched
     * {@code java.util} supertype - the two renderings the processor prints.
     * Every type is rendered through its canonical text, which names what is
     * written without resolving it further than the shape already has.
     *
     * @param slot the slot
     * @param holding how the slot is held, per {@link #holdingOf}
     * @return the storage type
     */
    static @NotNull String storageTypeText(@NotNull PsiFieldShape slot, @NotNull SlotHolding holding) {
        if (holding == SlotHolding.COLLECTED_SCRATCH) {
            return DeclaredBuilderShape.scratchContainerOf(slot.isMap, slot.isSet,
                canonicalText(slot.collectionElement), canonicalText(slot.mapKey), canonicalText(slot.mapValue));
        }
        String declared = declaredType(slot).getCanonicalText();
        return holding.isSupplier() ? DeclaredBuilderShape.supplierOf(declared) : declared;
    }

    /** A type argument's canonical text, or {@code null} where the shape read none. */
    private static @Nullable String canonicalText(@Nullable PsiType type) {
        return type == null ? null : type.getCanonicalText();
    }

    /**
     * Whether the slot's field keeps an initializer that reads instance state.
     *
     * @param target the annotated type
     * @param slot the slot to classify
     * @param retainInit the class-wide policy written on {@code @ClassBuilder}
     * @return whether the slot's default is computed on the instance
     */
    private static boolean instanceDefault(PsiClass target, PsiFieldShape slot, boolean retainInit) {
        PsiField field = null;
        for (PsiField own : ownFields(target)) {
            if (slot.name.equals(own.getName())) field = own;
        }
        PsiExpression initializer = field == null ? null : field.getInitializer();
        if (initializer == null) return false;
        PsiAnnotation written = WrittenAnnotations.findOnMember(field, ClassBuilderConstants.BUILDER_DEFAULT_FQN);
        boolean builderDefault = InstanceDefaults.builderDefault(
            written == null ? null : ClassBuilderConstants.booleanAttr(written, "value", true), retainInit);
        if (!InstanceDefaults.captures(builderDefault, slot.collector && slot.isCustomContainer)) return false;
        return InstanceDefaults.readsInstanceState(spelledNames(initializer), instanceMemberNames(target));
    }

    /**
     * Lists every name an initializer spells without a qualifier, and
     * {@code this} for each {@code this} expression, qualified or not - the
     * names the processor lists from the tree.
     *
     * @param initializer the field's initializer
     * @return the names, in source order
     */
    private static List<String> spelledNames(PsiExpression initializer) {
        List<String> out = new ArrayList<>();
        initializer.accept(new JavaRecursiveElementWalkingVisitor() {
            @Override
            public void visitReferenceElement(@NotNull PsiJavaCodeReferenceElement reference) {
                String name = reference.getReferenceName();
                if (reference.getQualifier() == null && name != null) out.add(name);
                super.visitReferenceElement(reference);
            }

            @Override
            public void visitReferenceExpression(@NotNull PsiReferenceExpression expression) {
                visitReferenceElement(expression);
            }

            @Override
            public void visitThisExpression(@NotNull PsiThisExpression expression) {
                out.add("this");
                super.visitThisExpression(expression);
            }

            @Override
            public void visitSuperExpression(@NotNull PsiSuperExpression expression) {
                // A qualified super is a select on the tree, whose name the
                // processor does not list.
                if (expression.getQualifier() == null) out.add("super");
                super.visitSuperExpression(expression);
            }
        });
        return out;
    }

    /**
     * Names every non-static field and method the target declares, and every
     * one its supertypes declare that it inherits, as the processor's element
     * model lists them - and every instance accessor another pass generates on
     * any of them, which neither model lists.
     *
     * @param target the annotated type
     * @return the member names
     */
    private static Set<String> instanceMemberNames(PsiClass target) {
        Set<String> names = new HashSet<>();
        collectInstanceMembers(target, true, names, new HashSet<>());
        return names;
    }

    /**
     * Adds a type's instance members to the set, then its supertypes'.
     *
     * <p>The accessors {@code @Getter}, {@code @Setter} and {@code @Lazy}
     * generate are provider members, which the type's own declarations leave
     * out, so they are named from the annotations written on each field and on
     * the type through {@link InstanceDefaults#generatedAccessorNames} - the
     * rule the processor asks of the same annotations. The annotations are
     * matched by their written names and read without resolving.
     *
     * @param type the type to read
     * @param own whether it is the target itself, whose private members count too
     * @param names the set being filled
     * @param visited the types already read
     */
    private static void collectInstanceMembers(PsiClass type, boolean own, Set<String> names,
                                               Set<PsiClass> visited) {
        if (!visited.add(type)) return;
        PsiAnnotation typeGetter = WrittenAnnotations.findOnMember(type, AccessorConstants.GETTER_FQN);
        PsiAnnotation typeSetter = WrittenAnnotations.findOnMember(type, AccessorConstants.SETTER_FQN);
        for (PsiField field : ownFields(type)) {
            if (instanceMember(field, own)) names.add(field.getName());
            PsiAnnotation getter = WrittenAnnotations.findOnMember(field, AccessorConstants.GETTER_FQN);
            PsiAnnotation setter = WrittenAnnotations.findOnMember(field, AccessorConstants.SETTER_FQN);
            names.addAll(InstanceDefaults.generatedAccessorNames(field.getName(),
                PsiTypes.booleanType().equals(field.getType()),
                field.hasModifierProperty(PsiModifier.STATIC),
                schemeOf(getter != null ? getter : typeGetter),
                schemeOf(setter != null ? setter : typeSetter),
                schemeOf(WrittenAnnotations.findOnMember(field, AccessorConstants.LAZY_FQN))));
        }
        for (PsiMethod method : GeneratedMemberFactory.ownMethods(type)) {
            if (!method.isConstructor() && instanceMember(method, own)) names.add(method.getName());
        }
        PsiClass superClass = type.getSuperClass();
        if (superClass != null) collectInstanceMembers(superClass, false, names, visited);
        for (PsiClass implemented : type.getInterfaces()) collectInstanceMembers(implemented, false, names, visited);
    }

    /** The naming scheme an accessor annotation writes, or {@code null} where there is no annotation. */
    private static @Nullable AccessorScheme schemeOf(@Nullable PsiAnnotation annotation) {
        return annotation == null
            ? null
            : AccessorScheme.resolve(AccessorConstants.style(annotation), AccessorConstants.name(annotation));
    }

    /** Whether the member is one the target sees on an instance - its own, or an inherited non-private one. */
    private static boolean instanceMember(PsiMember member, boolean own) {
        if (member.hasModifierProperty(PsiModifier.STATIC)) return false;
        return own || !member.hasModifierProperty(PsiModifier.PRIVATE);
    }

    /**
     * A variable's type as written, with the brackets a C-style declaration puts
     * after its name.
     *
     * <p>javac folds {@code String tags[]} into the declared type, so the
     * processor reads {@code String[]}; the type element PSI keeps in front of
     * the name covers {@code String} alone. The trailing dimensions are counted
     * off the variable's type, which PSI builds from the same brackets without
     * resolving anything.
     *
     * @param variable the field or parameter
     * @return the type as the processor reads it, or {@code null} when none is written
     */
    public static @Nullable String writtenTypeText(@NotNull PsiVariable variable) {
        PsiTypeElement written = variable.getTypeElement();
        if (written == null) return null;
        int trailing = variable.getType().getArrayDimensions() - written.getType().getArrayDimensions();
        return written.getText() + "[]".repeat(Math.max(0, trailing));
    }

    /** The class's own fields, without anything a provider contributed. */
    private static List<PsiField> ownFields(PsiClass declared) {
        return declared instanceof PsiExtensibleClass extensible
            ? extensible.getOwnFields()
            : List.of(declared.getFields());
    }

}
