package dev.sbs.classbuilder.mutate;

import com.sun.tools.javac.tree.JCTree;

import java.util.Collections;
import java.util.WeakHashMap;

/**
 * Tags JCTree nodes as "generated by {@code @ClassBuilder}" so:
 * <ul>
 *   <li>collision detection skips injection when a user already wrote a
 *       member with the same name/shape,</li>
 *   <li>downstream tooling or future processors can recognise our output
 *       without inspecting modifiers or annotations,</li>
 *   <li>the IDE-side {@code LineMarkerProvider} can mirror the "generated"
 *       attribution when it synthesises the same members.</li>
 * </ul>
 *
 * <p>javac's {@link JCTree} has no user-data slot, so marks live in a
 * process-local weak-identity set. Lifetime is bounded to the annotation-
 * processing round since the processor re-runs per compilation.
 */
public final class AstMarkers {

    private static final java.util.Set<JCTree> GENERATED =
        Collections.newSetFromMap(new WeakHashMap<>());

    private AstMarkers() {
    }

    /** Marks the given node as generated by {@code @ClassBuilder}. */
    public static void markGenerated(JCTree node) {
        if (node != null) GENERATED.add(node);
    }

    /** Returns {@code true} when the node was produced by the mutation pipeline. */
    public static boolean isGenerated(JCTree node) {
        return GENERATED.contains(node);
    }

}
