package dev.sbs.classbuilder.apt;

import javax.lang.model.element.TypeElement;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;

/**
 * Emits a concrete {@code <InterfaceName>Impl} class that implements an
 * interface annotated with {@code @ClassBuilder(generateImpl = true)} (the
 * default). Fields are derived from the interface's abstract zero-arg
 * accessors; the class is package-private, final, and provides an all-args
 * constructor, accessor methods that satisfy the interface contract, and
 * {@code equals}/{@code hashCode}/{@code toString} based on the fields.
 */
final class InterfaceImplEmitter {

    private InterfaceImplEmitter() {}

    static String emit(TypeElement target, String packageName, String implName, List<FieldSpec> fields) {
        StringBuilder sb = new StringBuilder(2048);
        sb.append("// Generated by @ClassBuilder - do not edit\n");
        if (!packageName.isEmpty()) sb.append("package ").append(packageName).append(";\n\n");

        TreeSet<String> imports = new TreeSet<>();
        imports.add("java.util.Objects");
        List<String> fieldTypes = new ArrayList<>(fields.size());
        for (FieldSpec f : fields) fieldTypes.add(simplifyType(f.typeDisplay, packageName, imports));
        for (String imp : imports) sb.append("import ").append(imp).append(";\n");
        if (!imports.isEmpty()) sb.append('\n');

        String interfaceName = target.getSimpleName().toString();
        sb.append("final class ").append(implName).append(" implements ").append(interfaceName).append(" {\n\n");

        // Fields
        for (int i = 0; i < fields.size(); i++) {
            sb.append("    private final ").append(fieldTypes.get(i)).append(' ').append(fields.get(i).name).append(";\n");
        }
        sb.append('\n');

        // All-args constructor (package-private)
        sb.append("    ").append(implName).append('(');
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(fieldTypes.get(i)).append(' ').append(fields.get(i).name);
        }
        sb.append(") {\n");
        for (FieldSpec f : fields) sb.append("        this.").append(f.name).append(" = ").append(f.name).append(";\n");
        sb.append("    }\n\n");

        // Accessor implementations
        for (int i = 0; i < fields.size(); i++) {
            FieldSpec f = fields.get(i);
            sb.append("    @Override public ").append(fieldTypes.get(i)).append(' ').append(f.name).append("() { return this.").append(f.name).append("; }\n");
        }
        sb.append('\n');

        // equals / hashCode / toString
        sb.append("    @Override public boolean equals(Object o) {\n");
        sb.append("        if (this == o) return true;\n");
        sb.append("        if (!(o instanceof ").append(implName).append(" other)) return false;\n");
        for (FieldSpec f : fields) sb.append("        if (!Objects.equals(this.").append(f.name).append(", other.").append(f.name).append(")) return false;\n");
        sb.append("        return true;\n    }\n\n");

        sb.append("    @Override public int hashCode() {\n        return Objects.hash(");
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(fields.get(i).name);
        }
        sb.append(");\n    }\n\n");

        sb.append("    @Override public String toString() {\n");
        sb.append("        return \"").append(implName).append("[\"\n");
        for (int i = 0; i < fields.size(); i++) {
            sb.append("            + \"").append(i == 0 ? "" : ", ").append(fields.get(i).name).append("=\" + this.").append(fields.get(i).name).append('\n');
        }
        sb.append("            + \"]\";\n    }\n\n");

        sb.append("}\n");
        return sb.toString();
    }

    private static String simplifyType(String typeStr, String packageName, TreeSet<String> imports) {
        StringBuilder out = new StringBuilder(typeStr.length());
        int i = 0;
        int n = typeStr.length();
        while (i < n) {
            int tokenStart = i;
            while (i < n && (Character.isJavaIdentifierPart(typeStr.charAt(i)) || typeStr.charAt(i) == '.')) i++;
            String token = typeStr.substring(tokenStart, i);
            if (!token.isEmpty() && token.indexOf('.') >= 0 && Character.isJavaIdentifierStart(token.charAt(0))) {
                out.append(considerImport(token, packageName, imports));
            } else {
                out.append(token);
            }
            if (i < n) {
                out.append(typeStr.charAt(i));
                i++;
            }
        }
        return out.toString();
    }

    private static String considerImport(String fqn, String packageName, TreeSet<String> imports) {
        if (fqn.startsWith("java.lang.") && fqn.lastIndexOf('.') == "java.lang".length()) {
            return fqn.substring("java.lang.".length());
        }
        int lastDot = fqn.lastIndexOf('.');
        if (lastDot < 0) return fqn;
        String pkg = fqn.substring(0, lastDot);
        String simple = fqn.substring(lastDot + 1);
        if (pkg.equals(packageName)) return simple;
        imports.add(fqn);
        return simple;
    }

}
