package dev.simplified.equality.editor;

import com.intellij.codeInsight.daemon.GutterMark;
import com.intellij.openapi.application.AccessToken;
import com.intellij.openapi.util.IconLoader;
import com.intellij.psi.PsiFile;
import com.intellij.testFramework.LightProjectDescriptor;
import com.intellij.testFramework.fixtures.LightJavaCodeInsightFixtureTestCase;
import dev.simplified.equality.inspect.WholeObjectTestSources;
import dev.simplified.testutil.JSvgErrorSuppressor;
import org.jetbrains.annotations.NotNull;

import javax.swing.Icon;

/**
 * Exercises {@link WholeObjectLineMarkerProvider}, whose every regression is
 * silent.
 *
 * <p>The marker emits provenance rather than resolution: nothing resolves
 * through it, nothing turns red when it is wrong, and the tooltip is the only
 * statement anywhere of which members an annotation compares or prints. So a
 * selection rule that drifts from the processor's produces a confidently wrong
 * description that no other test, and no compiler, contradicts - which is why
 * the assertions here are on the whole tooltip rather than on a fragment of it.
 */
public class WholeObjectLineMarkerProviderTest extends LightJavaCodeInsightFixtureTestCase {

    /**
     * The resource the provider names, duplicated deliberately: the test fails
     * loudly when the production constant moves rather than following it.
     */
    private static final String ICON_PATH = "/icons/generated.svg";

    private static final String EQUALITY = "@EqualsAndHashCode";
    private static final String TO_STRING = "@ToString";

    private AccessToken jsvgSuppressor;

    @Override
    protected @NotNull LightProjectDescriptor getProjectDescriptor() {
        return JAVA_17;
    }

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        // The gutter renders an SVG, which the platform's own loader reports as
        // a logged error on newer IDEs - and a logged error fails the test.
        jsvgSuppressor = JSvgErrorSuppressor.install();
        WholeObjectTestSources.install(myFixture);
    }

    @Override
    protected void tearDown() throws Exception {
        try {
            if (jsvgSuppressor != null) jsvgSuppressor.close();
        } finally {
            super.tearDown();
        }
    }

    // ------------------------------------------------------------------
    // Fixture helpers
    // ------------------------------------------------------------------

    private void configure(String path, String source) {
        PsiFile file = myFixture.addFileToProject(path, source);
        myFixture.configureFromExistingVirtualFile(file.getVirtualFile());
        myFixture.doHighlighting();
    }

    /** The one gutter this provider contributed for an annotation, failing when there is not exactly one. */
    private @NotNull String sole(String label) {
        return String.valueOf(gutter(label).getTooltipText());
    }

    private @NotNull GutterMark gutter(String label) {
        String prefix = "Generated by " + label;
        GutterMark found = null;
        for (GutterMark mark : myFixture.findAllGutters()) {
            String tooltip = mark.getTooltipText();
            if (tooltip == null || !tooltip.startsWith(prefix)) continue;
            assertNull("more than one " + label + " gutter on the configured file", found);
            found = mark;
        }
        assertNotNull("no " + label + " gutter on the configured file", found);
        return found;
    }

    private boolean marked(String label) {
        String prefix = "Generated by " + label;
        for (GutterMark mark : myFixture.findAllGutters()) {
            String tooltip = mark.getTooltipText();
            if (tooltip != null && tooltip.startsWith(prefix)) return true;
        }
        return false;
    }

    // ------------------------------------------------------------------
    // The equality tooltip
    // ------------------------------------------------------------------

    public void testMarkerDescribesAnAnnotatedClass() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public class Token {
                private String value;
                private long issued;
            }
            """);
        assertEquals("Generated by @EqualsAndHashCode"
                + "<br>Identity: this.getClass() == o.getClass()"
                + "<br>Compares: value, issued",
            sole(EQUALITY));
    }

    public void testIconResolvesToTheSharedResource() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public class Token { private String value; }
            """);
        assertSame("the gutter must reference " + ICON_PATH,
            IconLoader.getIcon(ICON_PATH, WholeObjectLineMarkerProvider.class),
            gutter(EQUALITY).getIcon());
    }

    /**
     * The wording a selection that reaches nothing produces, pinned because it
     * is also what a selection walk reading the wrong member list degrades to -
     * a description that is wrong and reads as deliberate.
     */
    public void testAnEmptySelectionSaysSoInFull() {
        configure("app/Marker.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public class Marker {
                private static final String TAG = "marker";
            }
            """);
        assertEquals("Generated by @EqualsAndHashCode"
                + "<br>Identity: this.getClass() == o.getClass()"
                + "<br>Compares no members - every instance compares equal to every other",
            sole(EQUALITY));
    }

    public void testInstanceOfIsSpelledAsATypeTest() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode(identity = EqualsAndHashCode.Identity.INSTANCE_OF)
            public class Token { private String value; }
            """);
        assertTrue(sole(EQUALITY).contains("<br>Identity: o instanceof Token<br>"));
    }

    public void testTheCooperatingRelationNamesTheHook() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode(identity = EqualsAndHashCode.Identity.INSTANCE_OF_CANEQUAL)
            public class Token { private String value; }
            """);
        assertTrue(sole(EQUALITY).contains(
            "o instanceof Token, asked back through a protected canEqual hook"));
    }

    /** The gutter has to say the hook degraded away, since nothing else does. */
    public void testTheCooperatingRelationOnAFinalRootTypeSaysTheHookIsGone() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode(identity = EqualsAndHashCode.Identity.INSTANCE_OF_CANEQUAL)
            public final class Token { private String value; }
            """);
        assertTrue(sole(EQUALITY).contains("no canEqual hook, since no subclass of a final root "
            + "type can override it"));
    }

    public void testTheMarkerFollowsTheNarrowingAttributes() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            import dev.simplified.annotations.EqualsExclude;
            @EqualsAndHashCode(exclude = "issued")
            public class Token {
                private String value;
                private long issued;
                @EqualsExclude private long checksum;
            }
            """);
        assertTrue(sole(EQUALITY).contains("<br>Compares: value"));
        assertFalse("the attribute takes it out", sole(EQUALITY).contains("issued"));
        assertFalse("and so does the marker", sole(EQUALITY).contains("checksum"));
    }

    public void testTheSuperCallIsShownWhenTheSuperclassSuppliesThePair() {
        myFixture.addFileToProject("app/Base.java",
            """
            package app;
            public class Base {
                @Override
                public boolean equals(Object o) { return this == o; }
                @Override
                public int hashCode() { return 0; }
            }
            """);
        configure("app/Child.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public class Child extends Base { private String label; }
            """);
        assertTrue(sole(EQUALITY).contains("<br>Calls super.equals and super.hashCode"));
    }

    public void testNoSuperCallIsShownWhenTheSuperclassSuppliesNeither() {
        myFixture.addFileToProject("app/Base.java",
            """
            package app;
            public class Base { protected int tag; }
            """);
        configure("app/Child.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public class Child extends Base { private String label; }
            """);
        assertFalse(sole(EQUALITY).contains("Calls super"));
    }

    public void testTheMemoAndTheAccessorReadsAreAnnounced() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode(cacheHashCode = true, useAccessors = true)
            public final class Token {
                private final String value = "";
                public String value() { return this.value; }
            }
            """);
        String tooltip = sole(EQUALITY);
        assertTrue(tooltip.contains("<br>Memoizes the hash in a transient $hashCode field"));
        assertTrue(tooltip.contains("<br>Reads each member through its declared accessor"));
    }

    // ------------------------------------------------------------------
    // Records - the shape the feature exists for
    // ------------------------------------------------------------------

    /**
     * A record's component-backed fields never appear among the fields the
     * class itself declares, so a member walk that reads only those answers
     * with nothing at all - and the tooltip then states the opposite of what is
     * generated, on the one target kind the annotation exists for.
     */
    public void testARecordIsDescribedThroughItsComponents() {
        configure("app/Pixels.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            import dev.simplified.annotations.EqualsExclude;
            @EqualsAndHashCode
            public record Pixels(int width, @EqualsExclude int height) { }
            """);
        assertEquals("Generated by @EqualsAndHashCode"
                + "<br>Identity: this.getClass() == o.getClass()"
                + "<br>Compares: width",
            sole(EQUALITY));
    }

    public void testARecordRendersItsComponents() {
        configure("app/Point.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString
            public record Point(int x, int y) { }
            """);
        assertEquals("Generated by @ToString<br>Renders: Point[x=..., y=...]", sole(TO_STRING));
    }

    // ------------------------------------------------------------------
    // The rendered line
    // ------------------------------------------------------------------

    public void testTheRenderedLineNamesEachMember() {
        configure("app/Ping.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString
            public class Ping {
                private String motd;
                private int players;
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Ping[motd=..., players=...]",
            sole(TO_STRING));
    }

    public void testTheLombokStyleAndUnlabelledFormAreShown() {
        configure("app/Ping.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString(style = ToString.Style.LOMBOK, includeFieldNames = false)
            public class Ping {
                private String motd;
                private int players;
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Ping(..., ...)", sole(TO_STRING));
    }

    /** Rank reorders the printed line, and the written name replaces the member's own. */
    public void testTheIncludeMarkerRenamesAndReordersATerm() {
        configure("app/Ping.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            import dev.simplified.annotations.ToStringInclude;
            @ToString
            public class Ping {
                private String motd;

                @ToStringInclude(name = "latency", rank = 1)
                public long ping() { return 0L; }
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Ping[latency=..., motd=...]",
            sole(TO_STRING));
    }

    /**
     * The two halves of the include marker over a list of plain fields, which
     * is where a shared selection can lose them quietly: the printed name and
     * the print order are the only two things the marker carries that no
     * report anywhere else reads, so nothing but this assertion notices them
     * going missing.
     *
     * <p>The trailing pair also pins the sort as the processor writes it -
     * stable, on descending rank - since {@code depth} must not overtake
     * {@code width} on the way past the ranked member.
     */
    public void testARankedIncludeLeadsALineOfPlainFields() {
        configure("app/Frame.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            import dev.simplified.annotations.ToStringInclude;
            @ToString
            public class Frame {
                private int width;
                @ToStringInclude(name = "h", rank = 5) private int height;
                private int depth;
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Frame[h=..., width=..., depth=...]",
            sole(TO_STRING));
    }

    /**
     * An include-marked method declared <b>between</b> two fields, which is the
     * one arrangement a fields-first walk cannot describe. The processor makes
     * a single pass over the target's enclosed elements, so the method is
     * emitted where it is written; a walk taking every field before every
     * method prints it last and the gutter states an order the build never
     * produces.
     *
     * <p>Every member here ranks zero deliberately: the sort is stable, so
     * nothing but the walk itself decides this line.
     */
    public void testAnIncludeMarkedMethodRendersWhereItIsDeclared() {
        configure("app/Frame.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            import dev.simplified.annotations.ToStringInclude;
            @ToString
            public class Frame {
                private int width;

                @ToStringInclude
                public int inset() { return 0; }

                private int depth;
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Frame[width=..., inset=..., depth=...]",
            sole(TO_STRING));
    }

    /**
     * A record component's marker propagates onto both its backing field and
     * its accessor, so an explicitly declared canonical accessor is the same
     * component read a second way rather than a second member. Counting both
     * prints the one component twice - and the printed name and print order the
     * marker carries are then applied to a term that should not be there at
     * all.
     */
    public void testAnExplicitCanonicalAccessorIsNotASecondTerm() {
        configure("app/Point.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            import dev.simplified.annotations.ToStringInclude;
            @ToString
            public record Point(int x, int y) {
                @ToStringInclude(name = "why", rank = 5)
                public int y() { return this.y; }
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Point[x=..., y=...]", sole(TO_STRING));
    }

    /**
     * A negative rank, which is how a member asks to be printed last. There is
     * no negative integer literal in the language - {@code -1} is a unary minus
     * over the literal {@code 1} - so an attribute reader accepting only the
     * literal resolves this to the default and leaves the member exactly where
     * it was written, with the annotation reading as if it had done something.
     */
    public void testANegativeRankSendsAMemberLast() {
        configure("app/Frame.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            import dev.simplified.annotations.ToStringInclude;
            @ToString
            public class Frame {
                @ToStringInclude(rank = -1) private int width;
                private int height;
                private int depth;
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Frame[height=..., depth=..., width=...]",
            sole(TO_STRING));
    }

    /**
     * A marker of the same simple name from another package leaves the member
     * where it was. The gutter resolves what it matches, which is what the
     * processor does - a description narrowed by an annotation the build never
     * reads is a member the tooltip claims is gone while it is still printed,
     * and nothing else in the file says otherwise.
     */
    public void testAForeignMarkerOfTheSameNameIsNotHonoured() {
        myFixture.addFileToProject("other/ToStringExclude.java",
            """
            package other;
            import java.lang.annotation.*;
            @Retention(RetentionPolicy.CLASS)
            @Target({ElementType.FIELD, ElementType.METHOD})
            public @interface ToStringExclude { }
            """);
        configure("app/Ping.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            import other.ToStringExclude;
            @ToString
            public class Ping {
                private String motd;
                @ToStringExclude private int players;
            }
            """);
        assertEquals("Generated by @ToString<br>Renders: Ping[motd=..., players=...]",
            sole(TO_STRING));
    }

    /**
     * The equality side reads the same selection and must not acquire the other
     * half's ordering with it. {@code @EqualsInclude} carries no rank on
     * purpose - a rank there would make an emitted hash depend on an ordering
     * rule nothing in the source shows - so an included method lands where it
     * was declared, after the fields.
     */
    public void testAnIncludedMethodJoinsTheComparedMembersInDeclarationOrder() {
        configure("app/Token.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            import dev.simplified.annotations.EqualsInclude;
            @EqualsAndHashCode
            public class Token {
                private String value;

                @EqualsInclude
                public int checksum() { return 0; }
            }
            """);
        assertEquals("Generated by @EqualsAndHashCode"
                + "<br>Identity: this.getClass() == o.getClass()"
                + "<br>Compares: value, checksum",
            sole(EQUALITY));
    }

    public void testTheSuperCallLeadsTheRenderedLine() {
        myFixture.addFileToProject("app/Base.java",
            """
            package app;
            public class Base {
                @Override
                public String toString() { return ""; }
            }
            """);
        configure("app/Child.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString
            public class Child extends Base { private String label; }
            """);
        assertEquals("Generated by @ToString<br>Renders: Child[super=..., label=...]",
            sole(TO_STRING));
    }

    /**
     * The one input the two annotations differ on, and the difference is
     * visible in a single file: state left out of serialization is still state
     * a dump wants, and never part of the value.
     */
    public void testTransientStateIsPrintedAndNotCompared() {
        configure("app/Ping.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            import dev.simplified.annotations.ToString;
            @EqualsAndHashCode
            @ToString
            public class Ping {
                private String motd;
                private transient String cache;
            }
            """);
        assertTrue(sole(EQUALITY).contains("<br>Compares: motd"));
        assertFalse(sole(EQUALITY).contains("cache"));
        assertEquals("Generated by @ToString<br>Renders: Ping[motd=..., cache=...]",
            sole(TO_STRING));
    }

    // ------------------------------------------------------------------
    // Target kinds
    // ------------------------------------------------------------------

    /**
     * The three kinds the processor refuses. Describing a member that will
     * never exist puts the gutter's own promise beside the red the inspection
     * reports on the same line.
     */
    public void testNoMarkerOnAnEnum() {
        configure("app/Mode.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString
            public enum Mode { A, B }
            """);
        assertFalse(marked(TO_STRING));
    }

    public void testNoMarkerOnAnInterface() {
        configure("app/Named.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public interface Named { String name(); }
            """);
        assertFalse(marked(EQUALITY));
    }

    /** Listed on its own rather than left to {@code isInterface()} to answer. */
    public void testNoMarkerOnAnAnnotationType() {
        configure("app/Marker.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString
            public @interface Marker { }
            """);
        assertFalse(marked(TO_STRING));
    }

    // ------------------------------------------------------------------
    // A hierarchy that does not terminate
    // ------------------------------------------------------------------

    /**
     * A cyclic {@code extends} is the ordinary state of a file mid-rename, and
     * the platform resolves one without complaint. The tooltip's superclass
     * walk runs on the daemon thread, so an unguarded loop there is a frozen
     * IDE rather than a wrong answer - a marker that is produced at all is the
     * assertion.
     */
    public void testASelfExtendingTargetStillProducesAMarker() {
        configure("app/Loop.java",
            """
            package app;
            import dev.simplified.annotations.EqualsAndHashCode;
            @EqualsAndHashCode
            public class Loop extends Loop { private String value; }
            """);
        assertTrue(marked(EQUALITY));
    }

    public void testMutuallyExtendingTargetsStillProduceAMarker() {
        myFixture.addFileToProject("app/Down.java",
            """
            package app;
            public class Down extends Up { }
            """);
        configure("app/Up.java",
            """
            package app;
            import dev.simplified.annotations.ToString;
            @ToString
            public class Up extends Down { private String value; }
            """);
        assertTrue(marked(TO_STRING));
    }

}
