package dev.sbs.classbuilder.editor;

import com.intellij.codeInsight.daemon.LineMarkerInfo;
import com.intellij.codeInsight.daemon.RelatedItemLineMarkerInfo;
import com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider;
import com.intellij.codeInsight.navigation.NavigationGutterIconBuilder;
import com.intellij.openapi.util.IconLoader;
import com.intellij.psi.PsiAnnotation;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiIdentifier;
import com.intellij.psi.PsiJavaCodeReferenceElement;
import dev.sbs.classbuilder.inspect.ClassBuilderConstants;
import org.jetbrains.annotations.NotNull;

import javax.swing.Icon;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

/**
 * Shows a gutter icon next to every {@code @ClassBuilder} annotation so it
 * is immediately discoverable that the class has synthesis active. Keeps
 * scope narrow for v1 - future iterations can extend markers to individual
 * field-level companions (e.g. {@code @Singular}).
 *
 * <p>The icon lives at {@code /icons/classbuilder_generated.svg}; replacing
 * that file is the only step needed to swap the art.
 */
public final class ClassBuilderLineMarkerProvider extends RelatedItemLineMarkerProvider {

    private static final Icon ICON = IconLoader.getIcon(
        "/icons/classbuilder_generated.svg",
        ClassBuilderLineMarkerProvider.class
    );

    @Override
    protected void collectNavigationMarkers(@NotNull PsiElement element,
                                            @NotNull Collection<? super RelatedItemLineMarkerInfo<?>> result) {
        // Anchor on the annotation's simple-name identifier so the marker
        // width matches the user-visible "@ClassBuilder" span, per IntelliJ
        // gutter-icon best practices (anchor on leaf identifiers, never on
        // compound elements).
        if (!(element instanceof PsiIdentifier identifier)) return;
        PsiElement ref = identifier.getParent();
        if (!(ref instanceof PsiJavaCodeReferenceElement javaRef)) return;
        PsiElement annotationElement = javaRef.getParent();
        if (!(annotationElement instanceof PsiAnnotation annotation)) return;
        if (!ClassBuilderConstants.ANNOTATION_FQN.equals(annotation.getQualifiedName())) return;

        RelatedItemLineMarkerInfo<PsiElement> info = NavigationGutterIconBuilder
            .create(ICON)
            .setTargets(Collections.singleton(annotation))
            .setTooltipText("Generated by @ClassBuilder")
            .createLineMarkerInfo(identifier);
        result.add(info);
    }

    @Override
    public String getName() {
        return "@ClassBuilder generated";
    }

    @Override
    public Icon getIcon() {
        return ICON;
    }

}
