package dev.sbs.classbuilder.apt;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.Compiler;
import com.google.testing.compile.JavaFileObjects;
import org.junit.Test;

import javax.tools.JavaFileObject;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * Verifies the {@code generateImpl} attribute on interface targets:
 * default generates both {@code <Name>Impl} and {@code <Name>Builder};
 * setting it to {@code false} skips the Impl and requires
 * {@code factoryMethod} to be set so {@code build()} has something to call;
 * no {@code factoryMethod} is a compile error.
 */
public class GenerateImplTest {

    private static Compilation compile(JavaFileObject... sources) {
        return Compiler.javac().withProcessors(new ClassBuilderProcessor()).compile(sources);
    }

    private static boolean hasGeneratedSource(Compilation c, String fqn) {
        return c.generatedSourceFile(fqn).isPresent();
    }

    private static String generatedSource(Compilation c, String fqn) {
        return c.generatedSourceFile(fqn)
            .map(f -> {
                try { return f.getCharContent(false).toString(); }
                catch (Exception e) { throw new AssertionError(e); }
            })
            .orElseThrow(() -> new AssertionError(
                "expected generated source '" + fqn + "' - generated files: " + c.generatedFiles()));
    }

    // ------------------------------------------------------------------
    // Default: Impl + Builder both emitted
    // ------------------------------------------------------------------

    @Test
    public void generateImplTrue_emitsImplAndBuilder() {
        JavaFileObject src = JavaFileObjects.forSourceLines("demo.Shape",
            "package demo;",
            "import dev.sbs.annotation.ClassBuilder;",
            "@ClassBuilder(validate = false)",
            "public interface Shape {",
            "    String name();",
            "    int sides();",
            "}");
        Compilation c = compile(src);
        assertThat(c).succeeded();
        assertTrue("ShapeImpl must be generated by default",
            hasGeneratedSource(c, "demo.ShapeImpl"));
        assertTrue("ShapeBuilder must be generated by default",
            hasGeneratedSource(c, "demo.ShapeBuilder"));
        // build() constructs the generated Impl.
        String builderSrc = generatedSource(c, "demo.ShapeBuilder");
        assertTrue("build() must instantiate ShapeImpl by default; saw:\n" + builderSrc,
            builderSrc.contains("new ShapeImpl("));
    }

    // ------------------------------------------------------------------
    // generateImpl = false + factoryMethod: Impl skipped, build() uses factory
    // ------------------------------------------------------------------

    @Test
    public void generateImplFalse_withFactoryMethod_skipsImplUsesFactory() {
        JavaFileObject src = JavaFileObjects.forSourceLines("demo.Widget",
            "package demo;",
            "import dev.sbs.annotation.ClassBuilder;",
            "@ClassBuilder(validate = false, generateImpl = false, factoryMethod = \"create\")",
            "public interface Widget {",
            "    String tag();",
            "    // User supplies the factory; its return type is the interface.",
            "    static Widget create(String tag) {",
            "        return new Widget() { public String tag() { return tag; } };",
            "    }",
            "}");
        Compilation c = compile(src);
        assertThat(c).succeeded();

        assertTrue("WidgetBuilder must still be generated",
            hasGeneratedSource(c, "demo.WidgetBuilder"));
        if (hasGeneratedSource(c, "demo.WidgetImpl")) {
            fail("generateImpl = false must skip WidgetImpl generation");
        }

        String builderSrc = generatedSource(c, "demo.WidgetBuilder");
        assertTrue("build() must delegate to Widget.create(...); saw:\n" + builderSrc,
            builderSrc.contains("Widget.create("));
        assertTrue("build() must NOT instantiate an Impl; saw:\n" + builderSrc,
            !builderSrc.contains("new WidgetImpl("));
    }

    // ------------------------------------------------------------------
    // generateImpl = false + no factoryMethod: compile error
    // ------------------------------------------------------------------

    @Test
    public void generateImplFalse_withoutFactoryMethod_compileError() {
        JavaFileObject src = JavaFileObjects.forSourceLines("demo.Broken",
            "package demo;",
            "import dev.sbs.annotation.ClassBuilder;",
            "@ClassBuilder(validate = false, generateImpl = false)",
            "public interface Broken {",
            "    String name();",
            "}");
        Compilation c = compile(src);
        // Expect an ERROR-kind diagnostic naming factoryMethod as the fix.
        // When compilation fails, generatedFiles() throws - the absence of
        // an Impl / Builder is implicit in the failure itself.
        assertThat(c).hadErrorContaining("generateImpl = false");
        assertThat(c).hadErrorContaining("factoryMethod");
    }
}
